### ISSUE TITLE
Binder! 

### ISSUE THREAD

**Issue by ericvd-ucb** [jhconning/Econ-Teach#1]
You should add  a binder link ( and button ) to your Readme!
https://mybinder.org/v2/gh/jhconning/Econ-Teach/master

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jhconning/Econ-Teach/master)

**Comment by jhconning** [comment]
Thanks. I finally got around to it with 7bc261be02a84c20edb8222156ae5dca6b46550d.  
There's now both a launch binder as a 'web app' (code hidden) option for interacting with the notebooks.  The latter using [voila dashboards and heroku](https://github.com/voila-dashboards/voila-heroku)
